version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: quick-schedule-app
    restart: always
    networks:
      - quick-schedule-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.21-alpine
    container_name: quick-schedule-nginx
    restart: always
    ports:
      - "9090:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - quick-schedule-network

networks:
  quick-schedule-network:
    driver: bridge