nginx:
  image: nginx:alpine
  container_name: quick-schedule-nginx
  restart: always
  ports:
    # Change this line
    - "9090:80" 
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
  depends_on:
    - nextjs
  networks:
    - quick-schedule-network