version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: quick-schedule-app
    restart: always
    # Using a custom port to avoid conflicts with other services
    expose:
      - "3000"
    # Only create an internal network, don't expose ports directly
    networks:
      - quick-schedule-network

  nginx:
    image: nginx:alpine
    container_name: quick-schedule-nginx
    restart: always
    ports:
      # Map to port 9090 to avoid conflicts with common ports
      - "9090:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - quick-schedule-network

networks:
  quick-schedule-network: