server {
    listen 80;
    server_name quick-schedule.tunapro.xyz;

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # For WebSockets support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# Default fallback server - will catch requests that don't match the server_name above
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    # Redirect all traffic to our main domain
    return 301 http://quick-schedule.tunapro.xyz$request_uri;
} 